version: 0.2
  
phases:
  pre_build:
    commands:
      - echo infra build plan
      - cd infra
      - npm install -g aws-cdk
      - cdk --version
      - env
  build:
    commands:
      - npm install
      - cdk diff --all
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
    - 'build/**/*'      