version: 0.2

phases:
  pre_build:
    commands:
      - echo Setting environment variables...
      - sed -i "s|SED_REPLACE_EXECUTION_ROLE_ARN|$EXECUTION_ROLE_ARN|g" taskdef.json
      - sed -i "s|SED_REPLACE_FAMILY|$FAMILY|g" taskdef.json
      - cat taskdef.json
  build:
    commands:
      - echo $IMAGE_TAG
      - npm install
      - cdk deploy --require-approval never
artifacts:
  files:
    - appspec.yaml
    - taskdef.json
  secondary-artifacts:
    ManifestArtifact:
      files:
        - appspec.yaml
        - taskdef.json 