version: 0.2

phases:
  pre_build:
    commands:
      - echo infra build plan
      - cd infra
      - ls -ltra
      - npm install -g aws-cdk
      - cdk --version
      - env
  build:
    commands:
      - echo $IMAGE_TAG
      - npm install
      - cdk deploy --require-approval never
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
    - 'build/**/*'      